[package]
name = "ping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    libp2p = "0.46.1"
    futures = "0.3.21"
    async-std = { version = "1.12.0", features = ["attributes"] }